/vis/open OGL

#/vis/viewer/set/autoRefresh false
#/vis/verbose errors

/vis/drawVolume worlds

/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
/vis/ogl/set/displayListLimit 1000000

/vis/scene/endOfEventAction accumulate 100
/gps/particle e-
/gps/number 1
/gps/direction 0 0 1
/gps/ene/mono 1 MeV
/gps/position 0. 0. 0. m
/run/beamOn 1
/gps/particle e-
/gps/number 1
/gps/direction 0 0 -1
/gps/ene/mono 1 MeV
/gps/position 0. 0. 100. m
/run/beamOn 1